version: 0.2

phases:
  install:
    commands:
      - echo install serverless framework
      - npm ci
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
      # Remove offline plugin to enable successful build (this plugin lives in dev dependencies and causes issues during build time)
      - sls plugin uninstall --name serverless-offline

      # - rm -rf node_modules/sharp
      # - npm install --arch=x64 --platform=linux sharp
      # - npm install @types/sharp

      - rm -rf node_modules/sharp
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp

      - npm outdated
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - npm run deploy-dev
  post_build:
    commands:
      - echo post build completed on `date`

cache:
  paths:
    - "./node_modules/**/*"
