version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #command: npm run start
    image: fthadia/meet-queue:latest
    container_name: meetqueuejs
    env_file: .env
    environment:
      NODE_ENV: dev-docker
      # Using the same DB as Rekognition service for now
      DB_USER: meet-queue-db-admin
      DB_PASSWORD: V38y4taFWsBGdmoB
      DB_URI: mongodb+srv://cluster0-evfkc.mongodb.net/meetqueuedb
    ports:
      - "80:3000"
    volumes:
      - .:/user/src/meet-queue
      - /usr/src/meet-queue/node_modules
    #working_dir: /Users/wilson/Documents/Fresh\ Turf/medical_project/aws-rekognition
