service: stlog-sftp-read
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  timeout: 30
  environment:
    NODE_ENV: dev
    AWS_SIGNED_URL_EXPIRES: "900"
    AWS_ACCESS_KEY_ID: AKIAVPKZCR7XR5ORZ364
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: ap-southeast-1
    AWS_S3_BUCKET_NAME: stlog-sftp
    AWS_S3_PREFIX_DOWNLOADED: Inbound/Downloaded/
    # max number of object keys to be returned
    AWS_S3_MAX_KEYS: 100
    AWS_DYNAMO_DB_TABLE_PROCESSED: sftp-processed
package:
  exclude:
    - src/**
    - .env
plugins:
  - serverless-offline
functions:
  showIP:
    handler: dist/bin/www.handler
    events:
      - http:
          path: /sftp/showIP
          method: GET
          cors: true
  checkNewFile:
    handler: dist/bin/www.handler
    events:
      - http:
          path: /sftp/checkNewFile
          method: GET
          cors: true
