service: vision-backend-app
custom:
  serverless-offline:
    useChildProcesses: true
  log-level:
    dev: debug
    prod: info
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  memorySize: 128
  timeout: 30
  environment:
    NODE_ENV: dev
    LOG_LEVEL: ${self:custom.log-level.${self:provider.stage}}
    BASE_PATH: "" #${self:provider.stage}
    AWS_SIGNED_URL_EXPIRES: "900"
    APP_AWS_REGION: ap-southeast-1
    # S3 Bucket
    AWS_S3_BUCKET_NAME: ${opt:stage, self:provider.stage, 'dev'}-{self:service}
    GOOGLE_APPLICATION_CREDENTIALS: ".key/sa-key.json" #lambda provides only /tmp/ directory
package:
  exclude:
    - src/**
    - .env
    # - node_modules/**
plugins:
  - serverless-offline
  # - serverless-domain-manager
functions:
  app:
    handler: dist/bin/www.handler
    timeout: 60
    events:
      - http:
          path: detect
          method: POST
          cors: true
      - http:
          path: detect_test
          method: POST
          cors: true
