dependencies:
# Install mongodb not mongodb-replicaset chart
#   - name: mongodb-replicaset
#     version: 3.x
#     repository: 'https://kubernetes-charts.storage.googleapis.com/'
#     condition: mongodb.enabled

  - name: mongodb
    version: 7.x
    repository: 'https://kubernetes-charts.storage.googleapis.com/'
    condition: dbEnabled
    